project_id = "olrejygsrwhclswrzvar"

[functions.upload-cover-image]
verify_jwt = true

[functions.upload-article-metadata]
verify_jwt = true

[functions.mint-to-story]
verify_jwt = true

[functions.upload-article-pdf]
verify_jwt = false

[functions.generate-cover-image]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false

[functions.orcid-callback]
verify_jwt = false